apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signbridge-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signbridge-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: signbridge-backend-service
                port:
                  number: 5000
